### PR TITLE
feat: remove rule to force *Action method naming in controller classes

### PR DESCRIPTION
**Pull request by shieldo**
While our code uses Symfony 3, removing the *Action suffix to controller names is not practical as the naming convention expects the suffix to be there. We could re-address once using Symfony 4, but until then the introduction of this rule would require a number of possibly unsafe changes to work round this convention. It's also not a bad convention, more that it just becomes a redundant constraint under Symfony 4.

### CODE REVIEW

**Comment by shieldo** [comment]
Would be good to get movement on this because the latest released versions of the coding standard contradict themselves in this area and are therefore somewhat unenforceable.

**Comment by gsdevme** [comment]
I think we might want to just delete the whole sniff if it’s not performing any asserts?

**Comment by shieldo** [comment]
That's a very good point! 🤦‍♂

**Comment by shieldo** [comment]
@gsdevme Revised to just remove the file, working under assumption this is working by doing a glob search for sniffs under a particular namespace.

**Pull request merged**
